### ISSUE TITLE
Add an option to hide the buttons in plain menu mode

### ISSUE THREAD

**Issue by vmalien** [adnantopal/slimmenu#65]
I just started to use your slimmmenu, and I like it. I've got a request:
Is it possible to add an option to hide the expand/collapse buttons in plain menu mode (and keep it in smartphone mode)?
The goal is to have narrower menus.
Thanks in advance.

**Comment by adnantopal** [comment]
You can do this with writing a few lines of CSS. The following CSS code should be enough. It will hide these buttons on the screens with bigger width than 768px.

``` css
@media (min-width: 768px) {
    ul.slimmenu li a {
        padding: 12px 16px;
    }
    ul.slimmenu li .sub-toggle {
        display: none;
    }
}
```
